parameters:
    google_geolocation.geolocation_api.class: Webinfopro\Bundle\GoogleGeolocationBundle\Geolocation\GeolocationApi
    # Max attempts to Google Geocoding API per day. Google's restriction is 2,500
    google_geolocation.geolocation_api.daily_limit: 2500
    # Max lifetime of geocoding result (hours). Set to 0 to disable caching
    google_geolocation.geolocation_api.cache_lifetime: 24    

services:
    google_geolocation.geolocation_api:
        class:      %google_geolocation.geolocation_api.class%
        calls:
            - [ setDocumentManager, [ @doctrine.odm.mongodb.document_manager ] ]
            - [ setDailyLimit, [ %google_geolocation.geolocation_api.daily_limit% ] ]
            - [ setCacheLifetime, [ %google_geolocation.geolocation_api.cache_lifetime% ] ]