<?php

namespace Webinfopro\Bundle\GoogleGeolocationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ApiLog
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiLogRepository extends EntityRepository
{
    public function getLogForDate(\DateTime $date = null)
    {
        if (true === is_null($date))
        {
            $date = new \DateTime();
        }

        $qb = $this->createQueryBuilder('a')
                   ->select('a')
                   ->where('a.created = :created')
                   ->setParameter('created', $date->format('Y-m-d'))
                   ->setMaxResults(1);

        try {
            return $qb->getQuery()
                      ->getSingleResult();
        } catch (\Doctrine\Orm\NoResultException $e) {
            return null;
        }
    }

    public function cleanCache()
    {
		$from = new \DateTime('today');

    	return $this->createQueryBuilder('l')
                    ->delete()
                    ->where('l.created < :expires')
                    ->setParameter('expires', $from)
                    ->getQuery()
                    ->execute();
    }
}
