<?php

namespace Google\GeolocationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ApiLog
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiLog extends EntityRepository
{
    public function getLogForDate(\DateTime $date = null)
    {
        if (true === is_null($date))
        {
            $date = new \DateTime();
        }

        $qb = $this->createQueryBuilder('a')
                   ->select('a')
                   ->where('a.created = :created')
                   ->setParameter('created', $date->format('Y-m-d'))
                   ->setMaxResults(1);

        try {
            return $qb->getQuery()
                      ->getSingleResult();
        } catch (\Doctrine\Orm\NoResultException $e) {
            return null;
        }
    }
}
