<?php

namespace Google\GeolocationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends EntityRepository
{
    public function getCachedLocation($search)
    {
        $qb = $this->createQueryBuilder('l')
                   ->select('l')
                   ->where('l.search = :search')
                   ->setParameter('search', $search)
                   ->setMaxResults(1);

        try {
            return $qb->getQuery()
                      ->getSingleResult();
        } catch (\Doctrine\Orm\NoResultException $e) {
            return null;
        }
    }
}